# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secret_key_base: 2c19bd96be49f1dcf1b3a0a547f27906a3fed80521a4dcf71f323d063a472177a2ea0524ea60b151835488c78204409df0adacf99aee09e4960b2fc4587ecb2f

test:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secret_key_base: 89ab99513aabc5d2b836a59241f86a7f996cfee73dc2a59434f4ea215dba092210e35b5fe6b5a6fd34e7fe96f95bd0e03ed7d2ae3c25a3f3ecf2f86014497a11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  cloudinary_cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  cloudinary_api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  cloudinary_api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
